version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: fazaconta
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./scripts/mongodb-init.sh:/init-replica.sh
      - ./dockervolume/mongodb:/data/db
    command: /init-replica.sh
    ports:
      - 27017:27017

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
