version: "3.8"

services:
  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_DATABASE: fazaconta
    volumes:
      - ./scripts/mongodb-init.sh:/init-replica.sh
      - mongo_data:/data/db
    command: /init-replica.sh
    ports:
      - 27017:27017

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
