version: "4"

services:
  mongodb:
    image: mongo:6
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: fazaconta
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./scripts/mongodb-init.sh:/init-replica.sh
      - ./dockervolume/mongodb:/data/db
    command: /init-replica.sh
    ports:
      - 27017:27017

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./dockervolume/redis:/data

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4583:4566-4583"
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - EDGE_PORT=4566
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=./tmp/localstack/data
    volumes:
      - "./scripts/aws-init.sh:/etc/localstack/init/ready.d/aws-init.sh"
      - "./dockervolume/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
