### Variables 
@host = http://0.0.0.0:8000
@route = groups

# @name createGroup
POST {{host}}/{{route}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiZGZlZDdhNjktZjdmOC00MzE5LWJlYzQtNmEzNDljNTczMDhkIiwibmFtZSI6IkpvXHUwMGUzbyBQZWRybyBMaW1hIFBpcmFqXHUwMGUxIiwibmlja25hbWUiOiJQaXJhalx1MDBlMSIsImVtYWlsIjoianBscDEwMEBob3RtYWlsLmNvbSIsInBob25lX251bWJlciI6IjcxOTk5MjU4MjI1IiwicHJvZmlsZV9waG90byI6eyJrZXkiOiJkNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic3JjIjoiaHR0cDovLzAuMC4wLjA6ODAwMC9maWxlcy9kNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic2l6ZSI6Mzk2MTg3LCJmaWxlbmFtZSI6Im1vb24tc3Vuc2V0LWhvcml6b24tMTkyMHgxMDgwLTE1NDk0LmpwZyIsImNvbnRlbnRfdHlwZSI6ImFwcGxpY2F0aW9uL2pwZyJ9LCJwaXgiOnsidHlwZSI6ImNwZl9jbnBqIiwidmFsdWUiOiI4NjIzMTEwMTUzMyJ9fSwiZXhwIjoxNzM2NzQ2NDMzfQ.0hmOfQHLunBDPMc_tWd9giLer2Qi5u9RbiCBgg7aK1o

--WebKitFormBoundary
Content-Disposition: form-data; name="title"

Bebidas
--WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="moon-sunset-horizon-1920x1080-15494.jpg"
Content-Type: application/jpg

< ./moon-sunset-horizon-1920x1080-15494.jpg
--WebKitFormBoundary--


###

@group_id = b2fa7ba5-06ad-4793-a1bc-74c7101f7720

# @name getGroupById
GET {{host}}/{{route}}/{{group_id}}

###

# @name getGroupsByUserId
GET {{host}}/{{route}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiZGZlZDdhNjktZjdmOC00MzE5LWJlYzQtNmEzNDljNTczMDhkIiwibmFtZSI6IkpvXHUwMGUzbyBQZWRybyBMaW1hIFBpcmFqXHUwMGUxIiwibmlja25hbWUiOiJQaXJhalx1MDBlMSIsImVtYWlsIjoianBscDEwMEBob3RtYWlsLmNvbSIsInBob25lX251bWJlciI6IjcxOTk5MjU4MjI1IiwicHJvZmlsZV9waG90byI6eyJrZXkiOiJkNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic3JjIjoiaHR0cDovLzAuMC4wLjA6ODAwMC9maWxlcy9kNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic2l6ZSI6Mzk2MTg3LCJmaWxlbmFtZSI6Im1vb24tc3Vuc2V0LWhvcml6b24tMTkyMHgxMDgwLTE1NDk0LmpwZyIsImNvbnRlbnRfdHlwZSI6ImFwcGxpY2F0aW9uL2pwZyJ9LCJwaXgiOnsidHlwZSI6ImNwZl9jbnBqIiwidmFsdWUiOiI4NjIzMTEwMTUzMyJ9fSwiZXhwIjoxNzM2NzQ2NDMzfQ.0hmOfQHLunBDPMc_tWd9giLer2Qi5u9RbiCBgg7aK1o

###

@group_id = 9fb1f2e4-613c-4142-9d52-d5ad979a8ef0

# @name addMember
GET {{host}}/{{route}}/{{group_id}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiZGZlZDdhNjktZjdmOC00MzE5LWJlYzQtNmEzNDljNTczMDhkIiwibmFtZSI6IkpvXHUwMGUzbyBQZWRybyBMaW1hIFBpcmFqXHUwMGUxIiwibmlja25hbWUiOiJQaXJhalx1MDBlMSIsImVtYWlsIjoianBscDEwMEBob3RtYWlsLmNvbSIsInBob25lX251bWJlciI6IjcxOTk5MjU4MjI1IiwicHJvZmlsZV9waG90byI6eyJrZXkiOiJkNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic3JjIjoiaHR0cDovLzAuMC4wLjA6ODAwMC9maWxlcy9kNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic2l6ZSI6Mzk2MTg3LCJmaWxlbmFtZSI6Im1vb24tc3Vuc2V0LWhvcml6b24tMTkyMHgxMDgwLTE1NDk0LmpwZyIsImNvbnRlbnRfdHlwZSI6ImFwcGxpY2F0aW9uL2pwZyJ9LCJwaXgiOnsidHlwZSI6ImNwZl9jbnBqIiwidmFsdWUiOiI4NjIzMTEwMTUzMyJ9fSwiZXhwIjoxNzM2NzA2NDM2fQ.aUHzBgbsJFARJCnFxKvDN0QYgJyE-KL8m96_pmCnNhQ

###