### Variables 
@host = http://0.0.0.0:8000
@route = groups

# @name createGroup
POST {{host}}/{{route}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiZGZlZDdhNjktZjdmOC00MzE5LWJlYzQtNmEzNDljNTczMDhkIiwibmFtZSI6IkpvXHUwMGUzbyBQZWRybyBMaW1hIFBpcmFqXHUwMGUxIiwibmlja25hbWUiOiJQaXJhalx1MDBlMSIsImVtYWlsIjoianBscDEwMEBob3RtYWlsLmNvbSIsInBob25lX251bWJlciI6IjcxOTk5MjU4MjI1IiwicHJvZmlsZV9waG90byI6eyJrZXkiOiJkNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic3JjIjoiaHR0cDovLzAuMC4wLjA6ODAwMC9maWxlcy9kNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic2l6ZSI6Mzk2MTg3LCJmaWxlbmFtZSI6Im1vb24tc3Vuc2V0LWhvcml6b24tMTkyMHgxMDgwLTE1NDk0LmpwZyIsImNvbnRlbnRfdHlwZSI6ImFwcGxpY2F0aW9uL2pwZyJ9LCJwaXgiOnsidHlwZSI6ImNwZl9jbnBqIiwidmFsdWUiOiI4NjIzMTEwMTUzMyJ9fSwiZXhwIjoxNzM2NjkwNTY3fQ.sH3vGLUKDBE9E3SQuA2wvvEdHmhPUiUmHJVcxcdZcaI

--WebKitFormBoundary
Content-Disposition: form-data; name="title"

Bebidas
--WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="moon-sunset-horizon-1920x1080-15494.jpg"
Content-Type: application/jpg

< ./moon-sunset-horizon-1920x1080-15494.jpg
--WebKitFormBoundary--


###

@group_id = b2fa7ba5-06ad-4793-a1bc-74c7101f7720

# @name getGroupById
GET {{host}}/{{route}}/{{group_id}}


###

# @name getGroupsByUserId
GET {{host}}/{{route}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWU0YjVhN2YtZDg2Mi00MjhjLTgwYjItYTg1M2QxMzNjYmE1IiwibmFtZSI6IkdhYnJpZWxsaSBWYWxlbGlhIiwibmlja25hbWUiOiJHYWJpIiwiZW1haWwiOiJnYWJyaWVsbGlzaWx2YTExMDJAZ21haWwuY29tIiwicGhvbmVfbnVtYmVyIjoiMjg5OTkzNDg1MzciLCJwcm9maWxlX3Bob3RvIjp7ImtleSI6ImY1YTYwZDVhLTg3MmUtNGIwNy1hYTFmLWE0NjllMDA5ZDYxMV9tb29uLXN1bnNldC1ob3Jpem9uLTE5MjB4MTA4MC0xNTQ5NC5qcGciLCJzcmMiOiJodHRwOi8vMC4wLjAuMDo4MDAwL2ZpbGVzL2Y1YTYwZDVhLTg3MmUtNGIwNy1hYTFmLWE0NjllMDA5ZDYxMV9tb29uLXN1bnNldC1ob3Jpem9uLTE5MjB4MTA4MC0xNTQ5NC5qcGciLCJzaXplIjozOTYxODcsImZpbGVuYW1lIjoibW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwiY29udGVudF90eXBlIjoiYXBwbGljYXRpb24vanBnIn0sInBpeCI6eyJ0eXBlIjoiZW1haWwiLCJ2YWx1ZSI6ImdhYnJpZWxsaXNpbHZhMTEwMkBnbWFpbC5jb20ifX0sImV4cCI6MTczNjY5MDgwNX0.uW1Rzk8p7KJKTt4kHaAjOk66n1fCkgTt6ubLoBcutEI

###

@group_id = 9fb1f2e4-613c-4142-9d52-d5ad979a8ef0

# @name addMember
GET {{host}}/{{route}}/{{group_id}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWU0YjVhN2YtZDg2Mi00MjhjLTgwYjItYTg1M2QxMzNjYmE1IiwibmFtZSI6IkdhYnJpZWxsaSBWYWxlbGlhIiwibmlja25hbWUiOiJHYWJpIiwiZW1haWwiOiJnYWJyaWVsbGlzaWx2YTExMDJAZ21haWwuY29tIiwicGhvbmVfbnVtYmVyIjoiMjg5OTkzNDg1MzciLCJwcm9maWxlX3Bob3RvIjp7ImtleSI6ImY1YTYwZDVhLTg3MmUtNGIwNy1hYTFmLWE0NjllMDA5ZDYxMV9tb29uLXN1bnNldC1ob3Jpem9uLTE5MjB4MTA4MC0xNTQ5NC5qcGciLCJzcmMiOiJodHRwOi8vMC4wLjAuMDo4MDAwL2ZpbGVzL2Y1YTYwZDVhLTg3MmUtNGIwNy1hYTFmLWE0NjllMDA5ZDYxMV9tb29uLXN1bnNldC1ob3Jpem9uLTE5MjB4MTA4MC0xNTQ5NC5qcGciLCJzaXplIjozOTYxODcsImZpbGVuYW1lIjoibW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwiY29udGVudF90eXBlIjoiYXBwbGljYXRpb24vanBnIn0sInBpeCI6eyJ0eXBlIjoiZW1haWwiLCJ2YWx1ZSI6ImdhYnJpZWxsaXNpbHZhMTEwMkBnbWFpbC5jb20ifX0sImV4cCI6MTczNjY5MDgwNX0.uW1Rzk8p7KJKTt4kHaAjOk66n1fCkgTt6ubLoBcutEI

###