### Variables 
@host = http://0.0.0.0:8000
@route = groups

# @name createGroup
POST {{host}}/{{route}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="title"

Bebidas
--WebKitFormBoundary
Content-Disposition: form-data; name="created_by_user_id"

151de6be-f7ac-4515-a4d2-b8e1c4ec5015
--WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="moon-sunset-horizon-1920x1080-15494.jpg"
Content-Type: application/jpg

< ./moon-sunset-horizon-1920x1080-15494.jpg
--WebKitFormBoundary--


###

@group_id = b2fa7ba5-06ad-4793-a1bc-74c7101f7720

# @name getGroupById
GET {{host}}/{{route}}/{{group_id}}


###

@user_id = 151de6be-f7ac-4515-a4d2-b8e1c4ec5015

# @name getGroupsByUserId
GET {{host}}/{{route}}/{{user_id}}/users


###