@host = http://0.0.0.0:8000
@route = sessions

# @name login
POST {{host}}/{{route}}/login
Content-Type: application/json

{
    "email": "jplp100@hotmail.com",
    "password": "123456"
}

###

# @name logout
POST {{host}}/{{route}}/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMTUxZGU2YmUtZjdhYy00NTE1LWE0ZDItYjhlMWM0ZWM1MDE1IiwibmFtZSI6IkpvXHUwMGUzbyBQZWRybyBMaW1hIFBpcmFqXHUwMGUxIiwibmlja25hbWUiOiJQaXJhalx1MDBlMSIsImVtYWlsIjoianBscDEwMEBob3RtYWlsLmNvbSIsInBob25lX251bWJlciI6IjcxOTk5MjU4MjI1IiwicHJvZmlsZV9waG90byI6eyJrZXkiOiJmYzJjNDBkMi1mYjMyLTQ4MWUtOGZmNS0wYjhhODRlYjhjZTVfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic3JjIjoiaHR0cDovLzAuMC4wLjA6ODAwMC9maWxlcy9mYzJjNDBkMi1mYjMyLTQ4MWUtOGZmNS0wYjhhODRlYjhjZTVfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic2l6ZSI6Mzk2MTg3LCJmaWxlbmFtZSI6Im1vb24tc3Vuc2V0LWhvcml6b24tMTkyMHgxMDgwLTE1NDk0LmpwZyIsImNvbnRlbnRfdHlwZSI6ImFwcGxpY2F0aW9uL2pwZyJ9LCJwaXgiOnsidHlwZSI6ImNwZl9jbnBqIiwidmFsdWUiOiI4NjIzMTEwMTUzMyJ9fSwiZXhwIjoxNzM2NjYxMTQwfQ.2Hobc76Vp_uyZU1Q_zRTt9nDaL1MQurEEdkM9rmSkbo
