### Variables 
@host = http://0.0.0.0:8000
@route = transactions

# @name createTransaction
POST {{host}}/{{route}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiZGZlZDdhNjktZjdmOC00MzE5LWJlYzQtNmEzNDljNTczMDhkIiwibmFtZSI6IkpvXHUwMGUzbyBQZWRybyBMaW1hIFBpcmFqXHUwMGUxIiwibmlja25hbWUiOiJQaXJhalx1MDBlMSIsImVtYWlsIjoianBscDEwMEBob3RtYWlsLmNvbSIsInBob25lX251bWJlciI6IjcxOTk5MjU4MjI1IiwicHJvZmlsZV9waG90byI6eyJrZXkiOiJkNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic3JjIjoiaHR0cDovLzAuMC4wLjA6ODAwMC9maWxlcy9kNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic2l6ZSI6Mzk2MTg3LCJmaWxlbmFtZSI6Im1vb24tc3Vuc2V0LWhvcml6b24tMTkyMHgxMDgwLTE1NDk0LmpwZyIsImNvbnRlbnRfdHlwZSI6ImFwcGxpY2F0aW9uL2pwZyJ9LCJwaXgiOnsidHlwZSI6ImNwZl9jbnBqIiwidmFsdWUiOiI4NjIzMTEwMTUzMyJ9fSwiZXhwIjoxNzM2NzMwMDQ4fQ.Cxm_OccAqSMnItQkg1O0NY9urxFk7t05IWdfYoO9oIc

{
    "group_id": "9fb1f2e4-613c-4142-9d52-d5ad979a8ef0",
    "title": "Reembolso",
    "amount": 1750,
    "transaction_type": "expense",
    "participants": [
        { "user_id": "5e4b5a7f-d862-428c-80b2-a853d133cba5", "amount": 100 },
        { "user_id": "dfed7a69-f7f8-4319-bec4-6a349c57308d", "amount": 1650 }  
        
    ]
}

###

@group_id = 9fb1f2e4-613c-4142-9d52-d5ad979a8ef0

# @name getTransactionsByGroupId
GET {{host}}/{{route}}/{{group_id}}/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiZGZlZDdhNjktZjdmOC00MzE5LWJlYzQtNmEzNDljNTczMDhkIiwibmFtZSI6IkpvXHUwMGUzbyBQZWRybyBMaW1hIFBpcmFqXHUwMGUxIiwibmlja25hbWUiOiJQaXJhalx1MDBlMSIsImVtYWlsIjoianBscDEwMEBob3RtYWlsLmNvbSIsInBob25lX251bWJlciI6IjcxOTk5MjU4MjI1IiwicHJvZmlsZV9waG90byI6eyJrZXkiOiJkNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic3JjIjoiaHR0cDovLzAuMC4wLjA6ODAwMC9maWxlcy9kNTMzYTEyMi02Mjk0LTQ3MmUtYTUzOC1kZjNkMGNlNDQ0YjJfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic2l6ZSI6Mzk2MTg3LCJmaWxlbmFtZSI6Im1vb24tc3Vuc2V0LWhvcml6b24tMTkyMHgxMDgwLTE1NDk0LmpwZyIsImNvbnRlbnRfdHlwZSI6ImFwcGxpY2F0aW9uL2pwZyJ9LCJwaXgiOnsidHlwZSI6ImNwZl9jbnBqIiwidmFsdWUiOiI4NjIzMTEwMTUzMyJ9fSwiZXhwIjoxNzM2NzI4MzUwfQ.rrqEwoVI9ymOszCWz2dRm2wIlFElSBvZ-zt77gFPZQE

###
