### Variables 
@host = http://0.0.0.0:8000
@route = transferences

# @name createTransference
POST {{host}}/{{route}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMTUxZGU2YmUtZjdhYy00NTE1LWE0ZDItYjhlMWM0ZWM1MDE1IiwibmFtZSI6IkpvXHUwMGUzbyBQZWRybyBMaW1hIFBpcmFqXHUwMGUxIiwibmlja25hbWUiOiJQaXJhalx1MDBlMSIsImVtYWlsIjoianBscDEwMEBob3RtYWlsLmNvbSIsInBob25lX251bWJlciI6IjcxOTk5MjU4MjI1IiwicHJvZmlsZV9waG90byI6eyJrZXkiOiJmYzJjNDBkMi1mYjMyLTQ4MWUtOGZmNS0wYjhhODRlYjhjZTVfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic3JjIjoiaHR0cDovLzAuMC4wLjA6ODAwMC9maWxlcy9mYzJjNDBkMi1mYjMyLTQ4MWUtOGZmNS0wYjhhODRlYjhjZTVfbW9vbi1zdW5zZXQtaG9yaXpvbi0xOTIweDEwODAtMTU0OTQuanBnIiwic2l6ZSI6Mzk2MTg3LCJmaWxlbmFtZSI6Im1vb24tc3Vuc2V0LWhvcml6b24tMTkyMHgxMDgwLTE1NDk0LmpwZyIsImNvbnRlbnRfdHlwZSI6ImFwcGxpY2F0aW9uL2pwZyJ9LCJwaXgiOnsidHlwZSI6ImNwZl9jbnBqIiwidmFsdWUiOiI4NjIzMTEwMTUzMyJ9fSwiZXhwIjoxNzM2NjkwMDE5fQ.-1QQ6YNDHKKo3_e3jRDb0Ri0P_GHm5a9yLdmSrVoY2o

{
    "group_id": "151de6be-f7ac-4515-a4d2-b8e1c4ec5015",
    "title": "Bebidas",
    "amount": 300,
    "transference_type": "expense",
    "participants": [
        { "user_id": "151de6be-f7ac-4515-a4d2-b8e1c4ec5015", "amount_to_pay": 150 },
        { "user_id": "649173a2-b39f-473c-b456-e71aa8ef57dd", "amount_to_pay": 150 }        
    ]
}

###

# @name getTransferences
GET {{host}}/{{route}}


###
